# Generated by Django 3.2.18 on 2023-03-15 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Cooking time must not be less than 1 minute')], verbose_name='Cooking time'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(default='#E26C2D', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Colour must be in HEX-format.')], verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', 'Slug must be in r"^[-a-zA-Z0-9_]+$" format')], verbose_name='Identifier'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_measurement_unit_for_name'),
        ),
    ]
