# Generated by Django 3.2.18 on 2023-03-19 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='colour',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#E26C2D', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', 'Colour must be in HEX-format.')], verbose_name='Colour'),
        ),
    ]
