# Generated by Django 3.2.18 on 2023-03-21 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Amount must not be less than 1 unit')], verbose_name='Recipe ingredient amount'),
        ),
    ]
